### PR TITLE
timeout setting for Request

### LINKED ISSUE #143: Provide an option for configuring `xhr.timeout`
It seems that both xhr2 and browsers support a `timeout` option. Should I provide a PR which adds this option to the `Request` (I mean `timeout :: Milliseconds`) type?

### PR DESCRIPTION
**Pull request by chekoopa**
A simple timeout feature with Maybe field in Request. Test case included. Closes #143.

It was easier than I've thought.

### CODE REVIEW

**Comment by chekoopa** [comment]
Had to force-push twice because of JS formatting fixes. Srry.

**Comment by thomashoneyman** [comment]
@chekoopa Libraries in the `purescript-contrib` organization only support ES5 in the FFI to ensure libraries can be used without a bundling step. I'm not sure if that's specifically the error you're seeing, but I do see `const` and `let` in there, which will parse with 0.13.8 but isn't ES5.

Do you mind switching over to use ES5 in the FFI file? Most likely that will also resolve the parse issue with the foreign JS as well. In this case it mostly looks like that comes down to swapping `var` for `const` / `let`.

**Comment by chekoopa** [comment]
@thomashoneyman Sure, done that, let's see what Travis would say.

**Comment by thomashoneyman** [comment]
Checked the documentation and [looks like setting 0 is the correct setting for "no timeout"](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout), so the `Maybe` encoding looks appropriate.

**Comment by chekoopa** [comment]
> Checked the documentation and [looks like setting 0 is the correct setting for "no timeout"](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout), so the `Maybe` encoding looks appropriate.

Yes, I've done it first without Maybe, but '0 ms' as a default value may create some misconceptions.

**Review by thomashoneyman — APPROVED** [review]
Thanks @chekoopa. I'd like to give @garyb a chance to take a look, but I think this looks good.

**Comment by garyb** [comment]
I think this should have been released as a breaking change - adding the field to `Request` means it will break for anyone who is constructing the value manually rather than overriding `defaultRequest`.

**Comment by thomashoneyman** [comment]
🤕 don't release late at night. I've updated the release to be `v11.0.0` as this didn't yet make it into Spago and it's only been a few hours.

**Pull request merged**
